version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
